const risk_levels = {
  automatico: "automatico",
  requiere_confirmacion: "requiere_confirmacion",
  solo_humano: "solo_humano",
};

function object_schema(properties, required = []) {
  return {
    type: "object",
    additionalProperties: true,
    properties,
    required,
  };
}

const ocr_input_schema = object_schema(
  {
    archivo_id: { type: "string" },
    tipo_documento_esperado: { type: "string" },
    campos_a_extraer: { type: "array", items: { type: "string" } },
    instrucciones: { type: "string" },
    confidence_threshold: { type: "number", minimum: 0, maximum: 1 },
  },
  ["archivo_id"],
);

const ocr_output_schema = object_schema({
  campos_extraidos: { type: "object" },
  confidence: { type: "number" },
  requiere_revision_humana: { type: "boolean" },
  observaciones: { type: "array", items: { type: "string" } },
  raw_text: { type: "string" },
});

export const action_catalog = [
  {
    action_id: "responder_conocimiento",
    nombre: "Responder con conocimiento",
    descripcion: "Responde usando business knowledge autorizado del negocio.",
    categoria: "conversacion",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema({ pregunta: { type: "string" }, knowledge_ids: { type: "array" } }, ["pregunta"]),
    output_schema: object_schema({ respuesta: { type: "string" }, fuentes_usadas: { type: "array" } }),
    permisos_requeridos: ["knowledge:read"],
    handler: "stub_responder_conocimiento",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "crear_contacto",
    nombre: "Crear contacto",
    descripcion: "Registra un contacto nuevo o prospecto.",
    categoria: "crm",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema({ nombre: { type: "string" }, telefono: { type: "string" }, email: { type: "string" } }),
    output_schema: object_schema({ contacto_id: { type: "string" } }),
    permisos_requeridos: ["contacts:write"],
    handler: "stub_crear_contacto",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "buscar_negocios",
    nombre: "Buscar negocios",
    descripcion: "Busca negocios o prospectos potenciales usando proveedores externos configurados.",
    categoria: "prospecting",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema(
      {
        query: { type: "string" },
        giro: { type: "string" },
        location: { type: "string" },
        ubicacion: { type: "string" },
        latitude: { type: "number" },
        longitude: { type: "number" },
        radius_meters: { type: "number" },
        max_results: { type: "number" },
        providers: { type: "array", items: { type: "string" } },
      },
      ["query"],
    ),
    output_schema: object_schema({
      negocios: { type: "array" },
      proveedores_usados: { type: "array" },
      errores_proveedor: { type: "array" },
      mensaje: { type: "string" },
    }),
    permisos_requeridos: ["prospects:search"],
    handler: "buscar_negocios",
    habilitada: true,
    habilitada_por_default: false,
    version: 1,
  },
  {
    action_id: "actualizar_contacto",
    nombre: "Actualizar contacto",
    descripcion: "Actualiza datos conocidos de un contacto.",
    categoria: "crm",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema({ contacto_id: { type: "string" }, cambios: { type: "object" } }, ["contacto_id"]),
    output_schema: object_schema({ actualizado: { type: "boolean" } }),
    permisos_requeridos: ["contacts:write"],
    handler: "stub_actualizar_contacto",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "crear_tarea",
    nombre: "Crear tarea",
    descripcion: "Crea una tarea interna de seguimiento.",
    categoria: "operacion",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema(
      {
        titulo: { type: "string" },
        descripcion: { type: "string" },
        responsable_id: { type: "string" },
        responsable: { type: "string" },
        due_at: { type: "string" },
        fecha_limite: { type: "string" },
        status: { type: "string" },
      },
      ["titulo"],
    ),
    output_schema: object_schema({ tarea_id: { type: "string" }, status: { type: "string" } }),
    permisos_requeridos: ["tasks:write"],
    handler: "crear_tarea",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "crear_recordatorio",
    nombre: "Crear recordatorio",
    descripcion: "Programa un recordatorio interno.",
    categoria: "seguimiento",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema({ titulo: { type: "string" }, fecha: { type: "string" } }, ["titulo"]),
    output_schema: object_schema({ recordatorio_id: { type: "string" } }),
    permisos_requeridos: ["reminders:write"],
    handler: "stub_crear_recordatorio",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "cambiar_estatus",
    nombre: "Cambiar estatus",
    descripcion: "Cambia estatus de un caso, prospecto o solicitud.",
    categoria: "operacion",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema({ entidad_id: { type: "string" }, estatus: { type: "string" } }, ["entidad_id", "estatus"]),
    output_schema: object_schema({ actualizado: { type: "boolean" } }),
    permisos_requeridos: ["status:write"],
    handler: "stub_cambiar_estatus",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "asignar_responsable",
    nombre: "Asignar responsable",
    descripcion: "Asigna responsable interno a una tarea, prospecto o caso.",
    categoria: "operacion",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema({ entidad_id: { type: "string" }, responsable_id: { type: "string" } }, ["entidad_id"]),
    output_schema: object_schema({ asignado: { type: "boolean" } }),
    permisos_requeridos: ["assignments:write"],
    handler: "stub_asignar_responsable",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "guardar_nota",
    nombre: "Guardar nota",
    descripcion: "Guarda una nota interna asociada al contacto o conversación.",
    categoria: "memoria",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema({ nota: { type: "string" }, entidad_id: { type: "string" } }, ["nota"]),
    output_schema: object_schema({ nota_id: { type: "string" } }),
    permisos_requeridos: ["notes:write"],
    handler: "guardar_nota",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "enviar_email",
    nombre: "Enviar email",
    descripcion: "Prepara y envia un email al cliente o equipo interno.",
    categoria: "comunicacion",
    nivel_riesgo: risk_levels.requiere_confirmacion,
    input_schema: object_schema({ to: { type: "string" }, subject: { type: "string" }, body: { type: "string" } }, ["to", "subject", "body"]),
    output_schema: object_schema({ email_id: { type: "string" }, sent: { type: "boolean" } }),
    permisos_requeridos: ["email:send"],
    handler: "stub_enviar_email",
    habilitada: true,
    habilitada_por_default: false,
    version: 1,
  },
  {
    action_id: "generar_resumen",
    nombre: "Generar resumen",
    descripcion: "Genera resumen operativo o comercial.",
    categoria: "analisis",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema({ contexto: { type: "object" }, formato: { type: "string" } }),
    output_schema: object_schema({ resumen: { type: "string" }, bullets: { type: "array" } }),
    permisos_requeridos: ["summaries:create"],
    handler: "generar_resumen",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "extraer_datos_de_imagen",
    nombre: "Extraer datos de imagen/documento",
    descripcion: "Extrae datos de fotos, screenshots, PDFs, tickets, constancias, comprobantes o documentos.",
    categoria: "documentos",
    nivel_riesgo: risk_levels.requiere_confirmacion,
    input_schema: ocr_input_schema,
    output_schema: ocr_output_schema,
    permisos_requeridos: ["files:read", "ocr:extract"],
    handler: "stub_extraer_datos_de_imagen",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "solicitar_aprobacion_humana",
    nombre: "Solicitar aprobación humana",
    descripcion: "Crea una solicitud de aprobación antes de ejecutar una acción sensible.",
    categoria: "seguridad",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema({ motivo: { type: "string" }, action_id: { type: "string" }, payload: { type: "object" } }, ["motivo"]),
    output_schema: object_schema({ aprobacion_id: { type: "string" }, status: { type: "string" } }),
    permisos_requeridos: ["approvals:create"],
    handler: "stub_solicitar_aprobacion_humana",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "crear_ticket",
    nombre: "Crear ticket",
    descripcion: "Crea un ticket interno de soporte u operación.",
    categoria: "operacion",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema({ titulo: { type: "string" }, descripcion: { type: "string" } }, ["titulo"]),
    output_schema: object_schema({ ticket_id: { type: "string" } }),
    permisos_requeridos: ["tickets:write"],
    handler: "stub_crear_ticket",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "guardar_archivo",
    nombre: "Guardar archivo",
    descripcion: "Registra un archivo recibido para uso posterior.",
    categoria: "documentos",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema({ archivo_id: { type: "string" }, metadata: { type: "object" } }, ["archivo_id"]),
    output_schema: object_schema({ guardado: { type: "boolean" } }),
    permisos_requeridos: ["files:write"],
    handler: "stub_guardar_archivo",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "generar_documento",
    nombre: "Generar documento",
    descripcion: "Genera un documento estructurado a partir de datos aprobados.",
    categoria: "documentos",
    nivel_riesgo: risk_levels.requiere_confirmacion,
    input_schema: object_schema({ tipo_documento: { type: "string" }, datos: { type: "object" } }, ["tipo_documento"]),
    output_schema: object_schema({ documento_id: { type: "string" } }),
    permisos_requeridos: ["documents:create"],
    handler: "stub_generar_documento",
    habilitada: true,
    habilitada_por_default: false,
    version: 1,
  },
  {
    action_id: "registrar_pago",
    nombre: "Registrar pago",
    descripcion: "Registra pago reportado por cliente o equipo.",
    categoria: "finanzas",
    nivel_riesgo: risk_levels.requiere_confirmacion,
    input_schema: object_schema({ monto: { type: "number" }, moneda: { type: "string" }, referencia: { type: "string" } }, ["monto"]),
    output_schema: object_schema({ pago_id: { type: "string" } }),
    permisos_requeridos: ["payments:write"],
    handler: "stub_registrar_pago",
    habilitada: true,
    habilitada_por_default: false,
    version: 1,
  },
  {
    action_id: "registrar_gasto",
    nombre: "Registrar gasto",
    descripcion: "Registra gasto operativo detectado.",
    categoria: "finanzas",
    nivel_riesgo: risk_levels.requiere_confirmacion,
    input_schema: object_schema({ monto: { type: "number" }, concepto: { type: "string" } }, ["monto", "concepto"]),
    output_schema: object_schema({ gasto_id: { type: "string" } }),
    permisos_requeridos: ["expenses:write"],
    handler: "stub_registrar_gasto",
    habilitada: true,
    habilitada_por_default: false,
    version: 1,
  },
  {
    action_id: "crear_solicitud_facturacion",
    nombre: "Crear solicitud de facturación",
    descripcion: "Crea una solicitud interna para emitir factura.",
    categoria: "facturacion",
    nivel_riesgo: risk_levels.requiere_confirmacion,
    input_schema: object_schema({ datos_fiscales: { type: "object" }, comprobantes: { type: "array" } }),
    output_schema: object_schema({ solicitud_facturacion_id: { type: "string" }, status: { type: "string" } }),
    permisos_requeridos: ["billing_requests:create"],
    handler: "stub_crear_solicitud_facturacion",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "validar_datos_fiscales",
    nombre: "Validar datos fiscales",
    descripcion: "Revisa que los datos fiscales mínimos estén completos.",
    categoria: "facturacion",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema({ rfc: { type: "string" }, razon_social: { type: "string" }, codigo_postal: { type: "string" } }),
    output_schema: object_schema({ valido: { type: "boolean" }, faltantes: { type: "array" } }),
    permisos_requeridos: ["billing:validate"],
    handler: "stub_validar_datos_fiscales",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
  {
    action_id: "revisar_documentos_requeridos",
    nombre: "Revisar documentos requeridos",
    descripcion: "Compara documentos recibidos contra una checklist.",
    categoria: "documentos",
    nivel_riesgo: risk_levels.automatico,
    input_schema: object_schema({ documentos_recibidos: { type: "array" }, documentos_requeridos: { type: "array" } }),
    output_schema: object_schema({ completos: { type: "boolean" }, faltantes: { type: "array" } }),
    permisos_requeridos: ["documents:review"],
    handler: "stub_revisar_documentos_requeridos",
    habilitada: true,
    habilitada_por_default: true,
    version: 1,
  },
];

const voice_actions = [
  "programar_llamada",
  "iniciar_llamada",
  "llamar_y_conectar",
  "llamar_y_confirmar",
  "registrar_resultado_llamada",
  "transcribir_llamada",
  "resumir_llamada",
  "escalar_llamada_a_humano",
].map((action_id) => ({
  action_id,
  nombre: action_id.replace(/_/g, " "),
  descripcion: "Acción de voz preparada para proveedor futuro, sin integración productiva todavía.",
  categoria: "voz",
  nivel_riesgo: action_id === "registrar_resultado_llamada" || action_id === "resumir_llamada"
    ? risk_levels.requiere_confirmacion
    : risk_levels.solo_humano,
  input_schema: object_schema({ telefono: { type: "string" }, motivo: { type: "string" }, metadata: { type: "object" } }),
  output_schema: object_schema({ status: { type: "string" }, provider: { type: "string" } }),
  permisos_requeridos: ["voice:future"],
  handler: `stub_${action_id}`,
  habilitada: true,
  habilitada_por_default: false,
  version: 1,
}));

export const action_registry = [...action_catalog, ...voice_actions];

export function list_actions() {
  return action_registry;
}

export function get_action(action_id) {
  return action_registry.find((action) => action.action_id === action_id) ?? null;
}

export function action_requires_confirmation(action) {
  return action?.nivel_riesgo === risk_levels.requiere_confirmacion || action?.nivel_riesgo === risk_levels.solo_humano;
}
