export const intents = [
  "day_start",
  "sales_update",
  "purchase",
  "inventory_update",
  "daily_close",
  "daily_note",
  "report_request",
  "lead_capture",
  "collect_information_start",
  "collect_information",
  "generate_document_request",
  "human_help",
  "unknown",
];
