function paquete(input) {
  return {
    version: 1,
    habilitado_por_default: true,
    ...input,
  };
}

export const agent_package_catalog = [
  paquete({
    paquete_id: "recepcionista_ai",
    nombre: "Recepcionista AI",
    descripcion: "Atiende preguntas frecuentes, captura datos, clasifica solicitudes y escala a humano.",
    categoria: "atencion",
    casos_de_uso: ["preguntas frecuentes", "captura de datos", "clasificacion de solicitudes", "handoff"],
    acciones_requeridas: ["responder_conocimiento", "crear_contacto", "actualizar_contacto", "guardar_nota", "solicitar_aprobacion_humana"],
    acciones_opcionales: ["crear_ticket", "crear_tarea", "enviar_email"],
    knowledge_base_sugerida: ["servicios", "horarios", "ubicaciones", "politicas", "preguntas frecuentes"],
    campos_recomendados: ["nombre", "telefono", "motivo_contacto"],
    reglas_de_escalamiento: ["cliente pide humano", "queja sensible", "pregunta fuera de knowledge"],
    nivel_complejidad: "bajo",
    precio_sugerido_min: 1000,
    precio_sugerido_max: 2000,
  }),
  paquete({
    paquete_id: "seguimiento_ventas",
    nombre: "Seguimiento de ventas",
    descripcion: "Detecta prospectos, califica interesados, crea tareas y prepara resumen para vendedor.",
    categoria: "ventas",
    casos_de_uso: ["calificacion de prospectos", "seguimiento", "resumen comercial"],
    acciones_requeridas: ["crear_contacto", "actualizar_contacto", "crear_tarea", "crear_recordatorio", "guardar_nota", "generar_resumen"],
    acciones_opcionales: ["enviar_email", "cambiar_estatus", "asignar_responsable"],
    knowledge_base_sugerida: ["servicios", "precios", "objeciones", "criterios de venta", "promociones"],
    campos_recomendados: ["nombre", "telefono", "interes", "presupuesto", "fecha_seguimiento"],
    reglas_de_escalamiento: ["descuento solicitado", "cliente molesto", "compra de alto valor"],
    nivel_complejidad: "medio",
    precio_sugerido_min: 1500,
    precio_sugerido_max: 3000,
  }),
  paquete({
    paquete_id: "agenda_facil",
    nombre: "Agenda fácil",
    descripcion: "Recibe solicitudes de cita, pide datos, crea recordatorios y prepara futura integración con calendario.",
    categoria: "agenda",
    casos_de_uso: ["solicitud de cita", "confirmacion", "recordatorios"],
    acciones_requeridas: ["crear_contacto", "crear_recordatorio", "guardar_nota", "solicitar_aprobacion_humana"],
    acciones_opcionales: ["enviar_email", "programar_llamada", "llamar_y_confirmar"],
    knowledge_base_sugerida: ["horarios", "sucursales", "servicios", "politicas de cita"],
    campos_recomendados: ["nombre", "telefono", "servicio", "fecha_preferida", "sucursal"],
    reglas_de_escalamiento: ["horario no disponible", "cambio de cita urgente", "cliente VIP"],
    nivel_complejidad: "medio",
    precio_sugerido_min: 1500,
    precio_sugerido_max: 3000,
  }),
  paquete({
    paquete_id: "factura_facil",
    nombre: "Factura fácil",
    descripcion: "Recibe datos fiscales, lee documentos y crea solicitudes internas de facturación.",
    categoria: "facturacion",
    casos_de_uso: ["solicitud de factura", "validacion fiscal", "lectura de constancias"],
    acciones_requeridas: ["validar_datos_fiscales", "extraer_datos_de_imagen", "crear_solicitud_facturacion", "guardar_archivo", "crear_ticket"],
    acciones_opcionales: ["enviar_email", "revisar_documentos_requeridos"],
    knowledge_base_sugerida: ["requisitos de facturacion", "politicas fiscales", "correos de encargados"],
    campos_recomendados: ["rfc", "razon_social", "codigo_postal", "uso_cfdi", "correo_facturacion"],
    reglas_de_escalamiento: ["datos fiscales incompletos", "archivo ilegible", "solicitud fuera de periodo"],
    nivel_complejidad: "medio",
    precio_sugerido_min: 2000,
    precio_sugerido_max: 3500,
  }),
  paquete({
    paquete_id: "documentos_facil",
    nombre: "Documentos fácil",
    descripcion: "Pide documentos, lee fotos/PDFs, detecta faltantes y arma checklist de expediente.",
    categoria: "documentos",
    casos_de_uso: ["expedientes", "checklist documental", "revision de archivos"],
    acciones_requeridas: ["guardar_archivo", "extraer_datos_de_imagen", "revisar_documentos_requeridos", "crear_ticket", "guardar_nota"],
    acciones_opcionales: ["generar_documento", "asignar_responsable"],
    knowledge_base_sugerida: ["documentos requeridos", "criterios de validacion", "formatos aceptados"],
    campos_recomendados: ["nombre", "tipo_tramite", "documentos_recibidos", "documentos_faltantes"],
    reglas_de_escalamiento: ["documento sensible", "documento ilegible", "inconsistencia en datos"],
    nivel_complejidad: "alto",
    precio_sugerido_min: 2500,
    precio_sugerido_max: 4000,
  }),
  paquete({
    paquete_id: "cobranza_suave",
    nombre: "Cobranza suave",
    descripcion: "Recuerda pagos, clasifica respuestas, crea promesas de pago y escala casos delicados.",
    categoria: "cobranza",
    casos_de_uso: ["recordatorios de pago", "promesas de pago", "seguimiento"],
    acciones_requeridas: ["crear_recordatorio", "guardar_nota", "cambiar_estatus", "generar_resumen", "solicitar_aprobacion_humana"],
    acciones_opcionales: ["registrar_pago", "enviar_email", "programar_llamada"],
    knowledge_base_sugerida: ["politicas de cobranza", "formas de pago", "mensajes autorizados"],
    campos_recomendados: ["nombre", "monto", "fecha_promesa_pago", "estatus_pago"],
    reglas_de_escalamiento: ["cliente molesto", "amenaza legal", "descuento o convenio"],
    nivel_complejidad: "alto",
    precio_sugerido_min: 2500,
    precio_sugerido_max: 4000,
  }),
  paquete({
    paquete_id: "reporte_diario",
    nombre: "Reporte diario",
    descripcion: "Resume conversaciones, prospectos nuevos, pendientes y acciones sugeridas para mañana.",
    categoria: "reportes",
    casos_de_uso: ["resumen diario", "pendientes", "prospectos sin respuesta"],
    acciones_requeridas: ["generar_resumen", "guardar_nota", "crear_tarea"],
    acciones_opcionales: ["enviar_email", "crear_recordatorio"],
    knowledge_base_sugerida: ["criterios de prioridad", "responsables", "horarios de corte"],
    campos_recomendados: ["fecha", "responsable", "canal", "prioridad"],
    reglas_de_escalamiento: ["pendientes críticos", "cliente sin respuesta", "monto alto"],
    nivel_complejidad: "bajo",
    precio_sugerido_min: 1000,
    precio_sugerido_max: 2000,
  }),
  paquete({
    paquete_id: "llamadas_y_conexion",
    nombre: "Llamadas y conexión",
    descripcion: "Paquete premium futuro para preparar llamadas, conectar prospectos y registrar resultados.",
    categoria: "voz",
    casos_de_uso: ["confirmar cita", "llamar prospecto", "conectar con vendedor", "registrar resultado"],
    acciones_requeridas: ["programar_llamada", "registrar_resultado_llamada", "solicitar_aprobacion_humana"],
    acciones_opcionales: ["iniciar_llamada", "llamar_y_conectar", "llamar_y_confirmar", "transcribir_llamada", "resumir_llamada", "escalar_llamada_a_humano"],
    knowledge_base_sugerida: ["scripts de llamada", "horarios permitidos", "reglas de consentimiento"],
    campos_recomendados: ["nombre", "telefono", "motivo_llamada", "horario_preferido"],
    reglas_de_escalamiento: ["sin consentimiento", "cobranza sensible", "cliente molesto"],
    nivel_complejidad: "alto",
    precio_sugerido_min: 3000,
    precio_sugerido_max: 5000,
    habilitado_por_default: false,
  }),
];

export function list_agent_packages({ include_disabled = false } = {}) {
  return agent_package_catalog.filter((paquete) => include_disabled || paquete.habilitado_por_default);
}

export function get_agent_package(paquete_id) {
  return agent_package_catalog.find((paquete) => paquete.paquete_id === paquete_id) ?? null;
}
